Repository chingu-voyages/v51-tier2-team-21, pull requests merged in 2024-09, with the labels that each got.

#15 Add Footer
  src/App.js
  src/components/Footer.tsx
  src/components/FooterDeveloperName.tsx
  src/data/DevelopersInfo.ts
  src/images.d.ts
  src/img/github.svg
  src/img/linkedin.svg
Labels: enhancement, user_story, task

#18 Feature/home-start-page
  public/assets/hero_img.svg
  public/assets/logo.png
  src/Layout.tsx
  src/components/FeaturesSection.tsx
  src/components/Header.tsx
  src/components/Hero.tsx
  src/components/TeamSection.tsx
  src/components/TestimonialsSection.tsx
  src/data/DevelopersInfo.ts
Labels: enhancement, user_story, task

#17 Add linters and GitHub actions to codebase
  .github/workflows/linters.yml
  .prettierignore
  .prettierrc
  README.md
  eslint.config.js
  package-lock.json
  package.json
  src/Layout.tsx
  src/components/ExpenseGroup.tsx
  src/components/ExpenseGroupList.tsx
  src/components/Footer.tsx
  src/components/FooterDeveloperName.tsx
  src/context/ExpenseGroupContext.tsx
  src/data/DevelopersInfo.ts
  src/images.d.ts
  src/index.js
Labels: enhancement

#19 Feature/landing-page
  src/components/Header.tsx
  src/components/Hero.tsx
  src/components/LandingPage.tsx
  src/components/TestimonialsSection.tsx
  src/data/DevelopersInfo.ts
  src/index.css
  src/index.js
Labels: bug, enhancement
